FROM registry.access.redhat.com/ubi8/python-38 AS base

ENV FLASK_DIR=/app \
    BUCKET_NAME="$BUCKET_NAME" \
    ENDPOINT_URL="$ENDPOINT_URL" \
    AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
    AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"

EXPOSE 8081
WORKDIR ${FLASK_DIR}

ADD ./app/requirements.txt ${FLASK_DIR}/requirements.txt

RUN pip config --global set global.progress_bar off && \
    pip install --requirement requirements.txt

COPY . /

ENTRYPOINT python
CMD app.py
